### ISSUE TITLE
Week 3 - Experiement 3 #1

### ISSUE THREAD

**Issue by appuCoding** [asadshahabuddin/CS5610#1]
I cant see output after clicking on spin the wheel.

**Comment by asadshahabuddin** [comment]
Hi,

![webdev 1](https://cloud.githubusercontent.com/assets/5422742/6139480/44bd0598-b15a-11e4-9b95-518d32b29ce4.png)

On clicking the 'Spin the Wheel' button, the movie name and description are successfully loaded as shown in the screenshot. It also loads the film poster, but the request suddenly seems to be forbidden for that image resource. The same is clearly indicated in the screenshot on the right-bottom corner (Google Chrome console). This wasn't the case when I had submitted my experiment and is specific for the movie.

P.S. An active internet connection is required to load the content on clicking the aforementioned button.

Please let me know if you have any queries/suggestions.

**Comment by appuCoding** [comment]
ok , I understand the issue, you can close the issue.
