### ISSUE TITLE
Upload Node.js Project Code into GitHub

### ISSUE THREAD

**Issue by appuCoding** [asadshahabuddin/CS5610#10]
Upload Node.js Project Code into GitHub and give link in your homepage for easy access

**Comment by asadshahabuddin** [comment]
Hi,

The code was already uploaded. Node.js code is present in the project folder under the directory named server. I have changed my home page such that the project link navigates to where my project is hosted on OpenShift. Finally, I have included a link to my final project source code (GitHub) on my home page's navigation bar.

Thank you for your suggestions.

**Comment by asadshahabuddin** [comment]
Please let me know if I can close this issue.

**Comment by appuCoding** [comment]
Please close the ticket.

Thanks,
Sneha Vankireddy
