### ISSUE TITLE
Make your home page responsive

### ISSUE THREAD

**Issue by appuCoding** [asadshahabuddin/CS5610#11]
Make your home page responsive, It is responsive but its not looking aligned in mobile

**Comment by asadshahabuddin** [comment]
Hi. I minimized the browser to the smallest possible width and viewed it on my iPhone too. It looks aligned. I am including the screenshots. Can you please tell me which specific part's alignment you are referring to?

![image](https://cloud.githubusercontent.com/assets/5422742/7108260/a24b4bce-e14e-11e4-842f-492179db60d4.png)

![img_3920](https://cloud.githubusercontent.com/assets/5422742/7108263/ae9d28e8-e14e-11e4-93b8-55985c4466e8.PNG)

Thanks for your input.

**Comment by appuCoding** [comment]
yeah , Your first screen shot doesn't have text aligned properly , You can close the issue if it is ok for you.

One word per line doesn't look good while viewing in the phone.

**Comment by asadshahabuddin** [comment]
I will try and resolve it. Thank you.

**Comment by asadshahabuddin** [comment]
I have resolved the issue. Please check and let me know if I can close it.

**Comment by appuCoding** [comment]
It looks good. Closed
